import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles";
import { HeaderWidget } from "@/widgets/header";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "bg-gray-100 dark:bg-gray-900")}>
        <HeaderWidget />
        <main className="container mx-auto px-20">{children}</main>
      </body>
    </html>
  );
};
